- name: Fetch kubeconfig from the remote node and set it up locally
  hosts: all
  tasks:
    - name: Ensure .kube directory exists in the current directory
      file:
        path: "/home/ubuntu/deployment/.kube"
        state: directory
        mode: '0755'

    - name: Ensure kubeconfig file is readable on the remote node
      file:
        path: /etc/rancher/rke2/rke2.yaml
        mode: '0644'
      become: true

    - name: Fetch kubeconfig file from remote node
      fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: "{{ playbook_dir }}/.kube/config"
        flat: yes
      become: true

    - name: Display message confirming fetch
      debug:
        msg: "Kubeconfig file fetched and stored as config in .kube directory"